''' 0: number
	1: name
	2: skill req
	3: skill rec
	4: quest req
	5: quest rec
'''
quests = []
quests.append([0,'',{},{},[],[]])

quests.append([1,"Cook's Assistant",{},{},[],[]])
quests.append([2,'Demon Slayer',{},{},[],[]])
quests.append([3,'The Restless Ghost',{},{},[],[]])
quests.append([4,'',{},{},[],[]])
quests.append([5,'',{},{},[],[]])
quests.append([6,'Shield of Arrav',{},{},[],[]])
quests.append([7,'',{},{},[],[]])
quests.append([8,'',{},{},[],[]])
quests.append([9,'',{},{},[],[]])
quests.append([10,'Stolen Hearts',{},{},[],[]])
quests.append([11,'',{},{},[],[]])
quests.append([12,'',{},{},[],[]])
quests.append([13,'',{},{},[],[]])
quests.append([14,'',{},{},[],[]])
quests.append([15,'Goblin Diplomacy',{},{},[],[]])
quests.append([16,"Pirate's Treasure",{},{},[],[]])
quests.append([17,'Dragon Slayer',{'QUEST POINTS':33},{'MAGIC':33,'PRAYER':43},[],[]])
quests.append([18,'Druidic Ritual',{},{},[],[]])
quests.append([19,'Lost City',{'CRAFTING':31,'WOODCUTTING':36},{},[],[]])
quests.append([20,"Witch's House",{},{},[],[]])
quests.append([21,"Merlin's Crystal",{},{},[],[]])
quests.append([22,"Heroes' Quest",{'COOKING':53,'FISHING':53,'HERBLORE':25,'MINING':50,'DEFENCE':25,
	'QUEST POINTS':56},{},[6,19,17,21,18],[]])
quests.append([23,'',{},{},[],[]])
quests.append([24,'Family Crest',{'CRAFTING':40,'SMITHING':40,'MINING':40,'MAGIC':59},{},[],[]])
quests.append([25,'',{},{},[],[]])
quests.append([26,'Fishing Contest',{'FISHING':10},{},[],[]])
quests.append([27,'',{},{},[],[]])
quests.append([28,'',{},{},[],[]])
quests.append([29,'',{},{},[],[]])
quests.append([30,'',{},{},[],[]])
quests.append([31,'Tree Gnome Village',{},{},[],[]])
quests.append([32,'Fight Arena',{},{},[],[]])
quests.append([33,'Hazeel Cult',{},{},[],[]])
quests.append([34,'',{},{},[],[]])
quests.append([35,'Plague City',{},{},[],[]])
quests.append([36,'Sea Slug',{'FIREMAKING':30},{},[],[]])
quests.append([37,'Waterfall Quest',{},{},[],[]])
quests.append([38,'Biohazard',{},{},[35],[]])
quests.append([39,'Jungle Potion',{'HERBLORE':3},{},[18],[]])
quests.append([40,'The Grand Tree',{},{},[],[31]])
quests.append([41,'Shilo Village',{'CRAFTING':20,'AGILITY':32},{'PRAYER':43},[39],[]])
quests.append([42,'Underground Pass',{'RANGED':25},{'MAGIC':34,'AGILITY':50,'PRAYER':43,'THIEVING':50},[38],[]])
quests.append([43,'',{},{},[],[]])
quests.append([44,'',{},{},[],[]])
quests.append([45,'',{},{},[],[]])
quests.append([46,'',{},{},[],[]])
quests.append([47,'Murder Mystery',{},{},[],[]])
quests.append([48,'The Dig Site',{'THIEVING':25,'AGILITY':10,'HERBLORE':10},{},[],[]])
quests.append([49,"Gertrude's Cat",{},{},[],[]])
quests.append([50,"Legends' Quest",{'AGILITY':50,'CRAFTING':50,'HERBLORE':45,'MINING':52,'PRAYER':42,
	'SMITHING':50,'STRENGTH':50,'THIEVING':50,'WOODCUTTING':50,'QUEST POINTS':108},{'PRAYER':43},[24,22,41,42,37],[]])
quests.append([51,'',{},{},[],[]])
quests.append([52,'Big Chompy Bird Hunting',{'COOKING':30,'RANGED':30,'FLETCHING':5},{},[],[]])
quests.append([53,'',{},{},[],[]])
quests.append([54,'Priest in Peril',{},{},[],[]])
quests.append([55,'Nature Spirit',{},{'CRAFTING':18,'PRAYER':10},[3,54],[]])
quests.append([56,'',{},{},[],[]])
quests.append([57,'',{},{},[],[]])
quests.append([58,'',{},{},[],[]])
quests.append([59,'',{},{},[],[]])
quests.append([60,'',{},{},[],[]])
quests.append([61,'',{},{},[],[]])
quests.append([62,'',{},{},[],[]])
quests.append([63,'Horror from the Deep',{'AGILITY':35},{'PRAYER':43,'CONSTITUTION':50},[],[]])
quests.append([64,'',{},{},[],[]])
quests.append([65,'Monkey Madness',{},{'PRAYER':43,'THIEVING':10},[40,31],[]])
quests.append([66,'',{},{},[],[]])
quests.append([67,'',{},{},[],[]])
quests.append([68,'',{},{},[],[]])
quests.append([69,'Creature of Fenkenstrain',{'CRAFTING':20,'THIEVING':25},{'SMITHING':20},[],[]])
quests.append([70,'',{},{},[],[]])
quests.append([71,'Ghosts Ahoy',{'AGILITY':25,'COOKING':20},{},[54,3],[]])
quests.append([72,'',{},{},[],[]])
quests.append([73,'',{},{},[],[]])
quests.append([74,'',{},{},[],[]])
quests.append([75,'',{},{},[],[]])
quests.append([76,'',{},{},[],[]])
# quests.append([77,'Desert Treasure',{'SLAYER':10,'FIREMAKING':50,},{},[],[]])
quests.append([78,"Icthlarin's Little Helper",{},{},[3,49,185],[]])
quests.append([79,'',{},{},[],[]])
quests.append([80,'Zogre Flesh Eaters',{'SMITHING':4,'HERBLORE':8,'STRENGTH':20,'RANGED':30},{'FLETCHING':30},[39,52],[]])
quests.append([81,'The Lost Tribe',{'AGILITY':13,'MINING':17,'THIEVING':13},{},[15],[]])
quests.append([82,'The Giant Dwarf',{'CRAFTING':12,'FIREMAKING':16,'MAGIC':33,'THIEVING':14},{},[],[]])
quests.append([83,'Recruitment Drive',{},{},[18],[]])
quests.append([84,'',{},{},[],[]])
quests.append([85,'',{},{},[],[]])
quests.append([86,'',{},{},[],[]])
quests.append([87,'A Tail of Two Cats',{},{},[78],[]])
quests.append([88,'Wanted!',{'QUEST POINTS':33},{},[54,81,83],[71]])
quests.append([89,'',{},{},[],[]])
quests.append([90,'Rum Deal',{'FARMING':40,'CRAFTING':42,'PRAYER':47,'FISHING':50,'SLAYER':42},{},[54,80],[]])
# quests.append([91,'Shadow of the Storm',{},{},[],[]])
quests.append([92,'',{},{},[],[]])
quests.append([93,'',{},{},[],[]])
quests.append([94,'',{},{},[],[]])
quests.append([95,'',{},{},[],[]])
quests.append([96,'',{},{},[],[]])
quests.append([97,"Enakhra's Lament",{'CRAFTING':50,'FIREMAKING':45,'MAGIC':13},{'MINING':45},[],[]])#wiki for details on skills
quests.append([98,'Cabin Fever',{'AGILITY':42,'CRAFTING':45,'SMITHING':50,'RANGED':40},{},[16,90],[]])
quests.append([99,'Fairy Tale I - Growing Pains',{},{},[19,55],[39]])
quests.append([100,'Recipe for Disaster',{'COOKING':70,'MAGIC':59,'THIEVING':53,'FISHING':53,'MINING':52,
	'CRAFTING':50,'FIREMAKING':50,'WOODCUTTING':50,'AGILITY':50,'RANGED':40,'HERBLORE':45,'FLETCHING':10,
	'SLAYER':10,'SMITHING':40,'QUEST POINTS':176},{},[1,15,26,49,91,52,38,2,47,55,20,19,50,65,77,63],[]])#dont know how to deal with this one
quests.append([101,'',{},{},[],[]])
quests.append([102,'',{},{},[],[]])
quests.append([103,'',{},{},[],[]])
quests.append([104,'',{},{},[],[]])
quests.append([105,'',{},{},[],[]])
quests.append([106,'Death to the Dorgeshuun',{'THIEVING':23,'AGILITY':23},{'COMBAT':80},[81],[]])
quests.append([107,'',{},{},[],[]])
quests.append([108,'',{},{},[],[]])
quests.append([109,'',{},{},[],[]])
quests.append([110,'',{},{},[],[]])
quests.append([111,'The Slug Menace',{'CRAFTING':30,'RUNECRAFTING':30,'SLAYER':30,'THIEVING':30},{},[36,88],[]])
quests.append([112,'',{},{},[],[]])
quests.append([113,'',{},{},[],[]])
quests.append([114,'',{},{},[],[]])
quests.append([115,'',{},{},[],[]])
quests.append([116,'',{},{},[],[]])
quests.append([117,'',{},{},[],[]])
quests.append([118,'',{},{},[],[]])
quests.append([119,'',{},{},[],[]])
quests.append([120,'',{},{},[],[]])
quests.append([121,'The Great Brain Robbery',{'CRAFTING':16,'CONSTRUCTION':30,'PRAYER':50},{},[69,100,98],[]])
quests.append([122,'',{},{},[],[]])
quests.append([123,'',{},{},[],[]])
quests.append([124,'Another Slice of H.A.M.',{'ATTACK':15,'PRAYER':25},{},[48,82,106],[]])
quests.append([125,'',{},{},[],[]])
quests.append([126,'',{},{},[],[]])
quests.append([127,'',{},{},[],[]])
quests.append([128,'',{},{},[],[]])
quests.append([129,'',{},{},[],[]])
quests.append([130,'Land of the Goblins',{'PRAYER':30,'AGILITY':36,'FISHING':36,'THIEVING':36,'HERBLORE':37},{},[124,26],[]])
quests.append([131,'',{},{},[],[]])
quests.append([132,'',{},{},[],[]])
quests.append([133,'',{},{},[],[]])
quests.append([134,'',{},{},[],[]])
quests.append([135,'',{},{},[],[]])
quests.append([136,'',{},{},[],[]])
quests.append([137,'',{},{},[],[]])
quests.append([138,'',{},{},[],[]])
quests.append([139,'',{},{},[],[]])
quests.append([140,'Rocking Out',{'AGILITY':60,'THIEVING':63,'CRAFTING':66,'SMITHING':69},{},[121],[]])
quests.append([141,'',{},{},[],[]])
quests.append([142,'',{},{},[],[]])
quests.append([143,'',{},{},[],[]])
quests.append([144,'',{},{},[],[]])
quests.append([145,'',{},{},[],[]])
quests.append([146,'',{},{},[],[]])
# quests.append([147,'While Guthix Sleeps',{},{},[],[]])#
quests.append([148,'',{},{},[],[]])
quests.append([149,'',{},{},[],[]])
quests.append([150,'The Chosen Commander',{'AGILITY':46,'STRENGTH':46,'THIEVING':46},{},[130],[]])
quests.append([151,'',{},{},[],[]])
quests.append([152,'',{},{},[],[]])
quests.append([153,'',{},{},[],[]])
quests.append([154,'',{},{},[],[]])
quests.append([155,'',{},{},[],[]])
quests.append([156,'',{},{},[],[]])
quests.append([157,'',{},{},[],[]])
quests.append([158,'',{},{},[],[]])
# quests.append([159,'The Temple at Senntisten',{},{},[],[]])#
quests.append([160,'',{},{},[],[]])
quests.append([161,'',{},{},[],[]])
quests.append([162,'',{},{},[],[]])
quests.append([163,'',{},{},[],[]])
quests.append([164,'',{},{},[],[]])
# quests.append([165,'Fairy Tale III - Orks Rift',{},{},[],[]])#
quests.append([166,'',{},{},[],[]])
quests.append([167,'',{},{},[],[]])
quests.append([168,'',{},{},[],[]])
quests.append([169,'',{},{},[],[]])
quests.append([170,'',{},{},[],[]])
quests.append([171,'',{},{},[],[]])
quests.append([172,'',{},{},[],[]])
quests.append([173,'',{},{},[],[]])
quests.append([174,'',{},{},[],[]])
quests.append([175,'',{},{},[],[]])
quests.append([176,'',{},{},[],[]])
quests.append([177,'Ritual of the Mahjarrat',{'CRAFTING':76,'AGILITY':77,'MINING':76},{},[147,159,87,111,140,33,32,165,97],[]])
quests.append([178,'',{},{},[],[]])
# quests.append([179,"The Firemaker's Curse",{},{},[],[]])#
quests.append([180,'',{},{},[],[]])
quests.append([181,'',{},{},[],[]])
quests.append([182,'',{},{},[],[]])
quests.append([183,'',{},{},[],[]])
quests.append([184,'',{},{},[],[]])
quests.append([185,'Diamond in the Rough',{},{},[10],[]])#isn't this just a remake??
quests.append([186,'',{},{},[],[]])
quests.append([187,'',{},{},[],[]])
# quests.append([188,'The World Wakes',{},{},[],[]])#
quests.append([189,'',{},{},[],[]])
quests.append([190,'',{},{},[],[]])
quests.append([191,'Missing, Presumed Death',{},{},[],[188,150]])
quests.append([192,'',{},{},[],[]])
quests.append([193,'Fate of the Gods',{'SUMMONING':67,'AGILITY':73,'DIVINATION':75,'SLAYER':76,'MAGIC':79},{},[191],[188,179,177]])
quests.append([194,'',{},{},[],[]])
quests.append([195,'',{},{},[],[]])
quests.append([196,'',{},{},[],[]])
quests.append([197,'',{},{},[],[]])
quests.append([198,'',{},{},[],[]])
quests.append([199,'',{},{},[],[]])

# quests.append([0,'',{},{},[],[]])

